CREATE TABLE note (
	uuid INTEGER PRIMARY KEY AUTOINCREMENT,
	content TEXT NOT NULL,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	mod_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted INTEGER NOT NULL DEFAULT 0p
);