CREATE TABLE note (
	uniqueID            INTEGER UNIQUE NOT NULL PRIMARY KEY AUTOINCREMENT,
	text                TEXT NOT NULL,
    truncatedText       VARCHAR(128) NOT NULL,
	createDate          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modDate             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted             INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE user (
    uniqueID            VARCHAR(128) UNIQUE NOT NULL PRIMARY KEY,
    hash                CHAR(256) NOT NULL
);